services:
  back:
    build:
      target: dev
    container_name: back-app-dev
    volumes:
      - ./../:/app:delegated
      - ./entrypoint.sh:/app/.docker/entrypoint.sh:ro
    networks:
      - devops-network
    env_file:
      - ../../DevOps/.env
    environment:
      - NODE_ENV=development

networks:
  devops-network:
    external: true
