name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    container:
      image: node:lts-alpine3.19
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Run Linter
        run: yarn lint
      - name: Format Code
        run: yarn format

  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: node:lts-alpine3.19
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Build Project
        run: yarn build
      - name: Run Unit Tests
        run: yarn test
      - name: Run e2e Tests
        run: yarn test:e2e

# deploy:
#   needs: build-and-test
#   runs-on: ubuntu-latest
#   container:
#     image: node:lts-alpine3.19
#   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
#   steps:
#     - uses: actions/checkout@v2
#     - name: Deploy to Server
#       run: echo "Deploy commands go here"
